//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CU132.CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidos
    {
        public int nroDetallePedido { get; set; }
        public int nroPedido { get; set; }
        public string detDetallePedido { get; set; }
        public int cantidad { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public Nullable<int> menu { get; set; }
        public Nullable<int> productoDeCarta { get; set; }
        public Nullable<int> tiempo { get; set; }
    }
}
