//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CU132.CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialEstado
    {
        public int id_historialEstado { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<System.DateTime> fechaHoraFin { get; set; }
        public Nullable<System.DateTime> fechaHoraInicio { get; set; }
        public Nullable<int> id_detallePedido { get; set; }
        public Nullable<int> id_pedido { get; set; }
    }
}
