//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CU132.CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int id_menu { get; set; }
        public int cantidadMinimaComensales { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaVigencia { get; set; }
        public Nullable<int> foto { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> precio { get; set; }
    }
}
