//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CU132.CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        public int numero { get; set; }
        public Nullable<int> capacidadComensales { get; set; }
        public Nullable<int> espacioQueOcupa { get; set; }
        public Nullable<int> forma { get; set; }
        public Nullable<int> filaEnPlano { get; set; }
        public Nullable<int> ordenEnPlano { get; set; }
        public Nullable<int> id_estado { get; set; }
    }
}
