//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CU132.CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoDeCarta
    {
        public int id_productoDeCarta { get; set; }
        public int esFavorito { get; set; }
        public string comentarios { get; set; }
        public Nullable<decimal> precio { get; set; }
        public int id_producto { get; set; }

        public void Crear()
        { 
            var context = new RestaurantEntities();
            var pdc = new ProductoDeCarta()
            {
                esFavorito = 0,
                comentarios = "Nada",
                precio = (decimal?)12.58,
                id_producto = 3
            };
            context.ProductoDeCarta.Add(pdc);
            context.SaveChanges();
        }
    }

    
}
