//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CU132.Entidades
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    
    public partial class DetallePedido : IComparable
    {
        public int nroDetallePedido { get; set; }
        public string detDetallePedido { get; set; }
        public int cantidad { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public Nullable<int> tiempo { get; set; }
        public int nroPedido { get; set; }
        public int historialEstado { get; set; }
        public Nullable<int> menu { get; set; }
        public Nullable<int> productoDeCarta { get; set; }
    
        public virtual HistorialEstado HistorialEstado { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual ProductoDeCarta ProductoDeCarta { get; set; }
        public virtual Pedido Pedidos { get; set; }

        

        public bool EstaEnPreparacion(Estado enPreparacion) {
            var historialEstadoUltimo = obtenerUltimoEstado();
            if (historialEstadoUltimo.Estado.Equals(enPreparacion))
                return true;
            return false;
        }

        /* El DetallePedido siempre va a estar ligado al último Historial */
        public HistorialEstado obtenerUltimoEstado() {
            return HistorialEstado;
        }

        public int CompareTo(object objAComparar)
        { 
        if (objAComparar == null) return 1;

        DetallePedido detallePedidoParametro = objAComparar as DetallePedido;
        if (detallePedidoParametro != null)
            return detallePedidoParametro.HistorialEstado.fechaHoraInicio.Value.CompareTo(this.HistorialEstado.fechaHoraInicio.Value);
        else
           throw new ArgumentException("El objeto no es un DetallePedido");
        }


    }
}
