//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CU132.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.DetallePedidos = new HashSet<DetallePedido>();
        }
    
        public int nroPedido { get; set; }
        public Nullable<int> cantComensales { get; set; }
        public string detPedido { get; set; }
        public Nullable<int> factura { get; set; }
        public Nullable<System.DateTime> fechaHoraPed { get; set; }
        public int mesa { get; set; }
        public int historialEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedidos { get; set; }
        public virtual HistorialEstado HistorialEstado { get; set; }
        public virtual Mesa Mesa { get; set; }
    }
}
